### ISSUE TITLE
Add support for factor-bundle plugin

### ISSUE THREAD

**Issue by gsantiago** [JS-DevTools/simplifyify#18]
It would be awesome if simplifyify could support the [factor bundle plugin](https://github.com/substack/factor-bundle). This saves a lot of bytes when We have to include multiple bundles in a same page.

Let's say I have two entry-points: `x.js` and `y.js` with both sharing modules in common.

We could run the following command to create the bundles:

`simplifyify source/*.js -o dist/*.bundle.js`

This will create two bundles: `x.bundle.js` and `y.bundle.js`. But both will have the same modules in common in each bundles. This is not good if We need to include both bundles in a same page.

So, we could add the factor-bundle option to resolve this problem:

`simplifyify source/*.js -o dist/*.bundle.js --factor-bundle dist/common.bundle.js`

This option would extract the common modules between the bundles into the `common.bundle.js` file.

**Comment by stringparser** [comment]
Actually I'm in the same situation. Searching for a browserify option for the common bundle end up here.

It might still be possible. In the `factor-bundle` readme it says:

```
you can pipe module-deps json directly into the factor-bundle command:

$ module-deps x.js y.js | factor-bundle \
  x.js -o bundle/x.js \
  y.js -o bundle/y.js \
  > bundle/common.js
or factor out an existing bundle already compiled by browserify:

$ browserify x.js y.js > bundle.js
$ browser-unpack < bundle.js | factor-bundle \
  x.js -o bundle/x.js \
  y.js -o bundle/y.js \
  > bundle/common.js
```

Have to try it.
